server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/board-db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    # Kafka 서버 주소
    bootstrap-servers: localhost:9092
    # 게시글 서비스에서는 메시지를 produce 하기만 함
    producer:
      # 메시지의 key 직렬화 방식 : 자바 객체를 문자열(String)로 변환해서 Kafka에 전송
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 메시지의 value 직렬화 방식 : 자바 객체를 문자열(String)로 변환해서 Kafka에 전송
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

client:
  user-service:
    url: http://localhost:8080
  point-service:
    url: http://localhost:8082